# Generated by Django 4.2.7 on 2023-12-26 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('building_id', models.AutoField(primary_key=True, serialize=False)),
                ('building_name', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'building',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('device_name', models.CharField(blank=True, max_length=30, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backend.building')),
            ],
            options={
                'db_table': 'device',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(choices=[('A', 'segmentation'), ('B', 'explosion_identify')], max_length=100)),
                ('image', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=45)),
                ('authority', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'user',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('time', models.DateTimeField(db_comment='采集数据时间', primary_key=True, serialize=False)),
                ('x', models.FloatField(db_comment='x方向数据')),
                ('y', models.FloatField(db_comment='y方向数据')),
                ('z', models.FloatField(db_comment='z方向数据')),
                ('device', models.ForeignKey(db_comment='传感器编号', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.device')),
            ],
            options={
                'db_table': 'log',
                'managed': True,
                'unique_together': {('time', 'x', 'y', 'z', 'device')},
            },
        ),
        migrations.CreateModel(
            name='Abnormal',
            fields=[
                ('time', models.DateTimeField(db_comment='数据采集时间', primary_key=True, serialize=False)),
                ('min', models.FloatField(db_comment='阈值下限')),
                ('max', models.FloatField(db_comment='阈值上限')),
                ('last_modified', models.DateTimeField(db_comment='上次修改时间')),
                ('data', models.FloatField(db_comment='异常值数据值')),
                ('direction', models.CharField(db_comment='数据方向(x/y/z)', max_length=255)),
                ('device', models.ForeignKey(db_comment='传感器编号', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.device')),
            ],
            options={
                'db_table': 'abnormal',
                'managed': True,
                'unique_together': {('time', 'device', 'min', 'max', 'last_modified', 'data', 'direction')},
            },
        ),
    ]
