# Generated by Django 4.2.7 on 2023-12-12 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="log",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="log",
            name="device",
            field=models.ForeignKey(
                db_comment="传感器编号",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="backend.device",
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="time",
            field=models.DateTimeField(
                db_comment="采集数据时间", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="log",
            name="x",
            field=models.FloatField(db_comment="x方向数据"),
        ),
        migrations.AlterField(
            model_name="log",
            name="y",
            field=models.FloatField(db_comment="y方向数据"),
        ),
        migrations.AlterField(
            model_name="log",
            name="z",
            field=models.FloatField(db_comment="z方向数据"),
        ),
        migrations.AlterUniqueTogether(
            name="log",
            unique_together={("time", "x", "y", "z", "device")},
        ),
        migrations.RemoveField(
            model_name="log",
            name="id",
        ),
        migrations.CreateModel(
            name="Abnormal",
            fields=[
                (
                    "time",
                    models.DateTimeField(
                        db_comment="数据采集时间", primary_key=True, serialize=False
                    ),
                ),
                ("min", models.FloatField(db_comment="阈值下限")),
                ("max", models.FloatField(db_comment="阈值上限")),
                (
                    "last_modified",
                    models.DateTimeField(auto_now=True, db_comment="上次修改时间"),
                ),
                ("data", models.FloatField(db_comment="异常值数据值")),
                (
                    "direction",
                    models.CharField(db_comment="数据方向(x/y/z)", max_length=255),
                ),
                (
                    "device",
                    models.ForeignKey(
                        db_comment="传感器编号",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="backend.device",
                    ),
                ),
            ],
            options={
                "db_table": "abnormal",
                "managed": True,
                "unique_together": {
                    (
                        "time",
                        "device",
                        "min",
                        "max",
                        "last_modified",
                        "data",
                        "direction",
                    )
                },
            },
        ),
    ]
