# Generated by Django 4.2.7 on 2023-12-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_log_unique_together_alter_log_device_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abnormal",
            name="last_modified",
            field=models.DateTimeField(db_comment="上次修改时间"),
        ),
    ]
