# Generated by Django 4.2.7 on 2023-12-11 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                ("building_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "building_name",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
            ],
            options={
                "db_table": "building",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                ("device_id", models.AutoField(primary_key=True, serialize=False)),
                ("device_name", models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                "db_table": "device",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
                ("x", models.FloatField()),
                ("y", models.FloatField()),
                ("z", models.FloatField()),
            ],
            options={
                "db_table": "log",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "email",
                    models.CharField(max_length=45, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=45)),
                ("authority", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "user",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="title",
        ),
    ]
